'use client';

import React, { useEffect, useState } from 'react';
import { collection, getDocs, limit, orderBy, query } from 'firebase/firestore';
import { firestore } from '@/lib/firebase';
import { firestoreDate } from '@/lib/organization-data';
import { EmptyState, ErrorState, formatDate, LoadingState } from './ConsolePrimitives';

type AuditLog = { id: string; action?: string; actorEmail?: string; actorRole?: string; targetType?: string; targetId?: string; organizationId?: string; createdAt?: string };
export function AuditLogsModule() { const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { const load = async () => { try { let snapshot; try { snapshot = await getDocs(query(collection(firestore, 'platformAuditLogs'), orderBy('createdAt', 'desc'), limit(100))); } catch { snapshot = await getDocs(query(collection(firestore, 'platformAuditLogs'), limit(100))); } setLogs(snapshot.docs.map((item) => { const data = item.data(); return { id: item.id, action: data.action, actorEmail: data.actorEmail, actorRole: data.actorRole, targetType: data.targetType, targetId: data.targetId, organizationId: data.organizationId, createdAt: firestoreDate(data.createdAt) }; })); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load audit logs.'); } finally { setLoading(false); } }; void load(); }, []); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} />; return !logs.length ? <EmptyState title="No audit activity yet" message="Administrative actions will appear here once the secure server API is connected." /> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-gray-200 bg-gray-50 text-[10px] uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3">Action</th><th>Admin</th><th>Target</th><th>Organization</th><th>Created</th></tr></thead><tbody className="divide-y divide-gray-100">{logs.map((log) => <tr key={log.id}><td className="px-5 py-4 font-bold">{log.action || '—'}</td><td>{log.actorEmail || '—'}<span className="ml-2 text-xs text-gray-400">{log.actorRole || ''}</span></td><td>{log.targetType || '—'} {log.targetId ? `· ${log.targetId}` : ''}</td><td>{log.organizationId || '—'}</td><td>{formatDate(log.createdAt)}</td></tr>)}</tbody></table></div>; }
