'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { fetchOrganizations } from '@/lib/organization-data';
import { evaluateOrganizationLicense } from '@/lib/license';
import { Organization } from '@/lib/types';
import { EmptyState, ErrorState, formatDate, LoadingState, StatusBadge } from './ConsolePrimitives';

export function LicensingModule() { const [items, setItems] = useState<Organization[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { fetchOrganizations().then(setItems).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load licensing data.')).finally(() => setLoading(false)); }, []); const filtered = useMemo(() => items.filter((org) => org.name.toLowerCase().includes(query.toLowerCase())), [items, query]); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} />; return <div className="space-y-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search organizations" className="w-full rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500" />{!filtered.length ? <EmptyState title="No license records found" message="License data is read from the authoritative organization documents." /> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-gray-200 bg-gray-50 text-[10px] uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3">Organization</th><th>Plan</th><th>Status</th><th>Expiration</th><th>Seat limit</th></tr></thead><tbody className="divide-y divide-gray-100">{filtered.map((org) => { const evaluation = evaluateOrganizationLicense(org); return <tr key={org.id}><td className="px-5 py-4 font-bold">{org.name}</td><td>{org.license?.planId || '—'}</td><td><StatusBadge status={evaluation.status} /></td><td>{formatDate(org.license?.expiresAt || org.license?.trialEndsAt)}</td><td>{org.license?.seatLimit ?? '—'}</td></tr>; })}</tbody></table></div>}</div>; }
