'use client';

import React, { useState } from 'react';
import type { ExistingOrganizationUser } from '@/lib/console-api';
import type { Organization, OrganizationMember, OrganizationMemberRole } from '@/lib/types';

const memberStatuses = ['active', 'pending', 'inactive', 'suspended', 'archived', 'disabled'] as const;
const timezoneOptions = ['Asia/Manila', 'Asia/Singapore', 'Asia/Tokyo', 'America/New_York', 'America/Los_Angeles', 'Europe/London', 'Europe/Berlin', 'Australia/Sydney', 'UTC'];
const currencyOptions = ['PHP', 'USD', 'EUR', 'GBP', 'SGD', 'AUD', 'JPY', 'CAD', 'CNY', 'HKD', 'KRW', 'INR', 'NZD', 'CHF', 'THB', 'MYR', 'IDR'];

function DialogShell({ title, children, busy, onClose, onSubmit, submitLabel, busyLabel = 'Saving…' }: { title: string; children: React.ReactNode; busy: boolean; onClose: () => void; onSubmit: () => void | Promise<void>; submitLabel: string; busyLabel?: string }) {
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-label={title}><form onSubmit={(event) => { event.preventDefault(); void onSubmit(); }} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black text-gray-950">{title}</h2>{children}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={busy} className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-bold text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500">Cancel</button><button type="submit" disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50">{busy ? busyLabel : submitLabel}</button></div></form></div>;
}

export function OrganizationProfileDialog({ organization, busy, onClose, onSubmit }: { organization: Organization; busy: boolean; onClose: () => void; onSubmit: (payload: { name: string; businessType: string; currency: string; timezone: string; reason?: string }) => void }) {
  const [name, setName] = useState(organization.name);
  const [businessType, setBusinessType] = useState(organization.businessType || '');
  const [currency, setCurrency] = useState(organization.currency || '');
  const [timezone, setTimezone] = useState(organization.timezone || '');
  const [reason, setReason] = useState('');
  const [error, setError] = useState('');
  const submit = () => { if (!name.trim()) return setError('Business name is required.'); setError(''); onSubmit({ name: name.trim(), businessType: businessType.trim(), currency: currency.trim(), timezone: timezone.trim(), reason: reason.trim() || undefined }); };
  const timezones = organization.timezone && !timezoneOptions.includes(organization.timezone) ? [organization.timezone, ...timezoneOptions] : timezoneOptions;
  const currencies = organization.currency && !currencyOptions.includes(organization.currency) ? [organization.currency, ...currencyOptions] : currencyOptions;
  return <DialogShell title="Edit Organization" busy={busy} onClose={onClose} onSubmit={submit} submitLabel="Save changes"><p className="mt-1 text-sm text-gray-500">Only supported organization metadata can be changed. Organization ID and slug remain immutable.</p><label className="mt-5 block text-sm font-bold">Business name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><label className="mt-4 block text-sm font-bold">Business type<input value={businessType} onChange={(event) => setBusinessType(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><label className="mt-4 block text-sm font-bold">Currency<select value={currency} onChange={(event) => setCurrency(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"><option value="">Not Set</option>{currencies.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Timezone<select value={timezone} onChange={(event) => setTimezone(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"><option value="">Not Set</option>{timezones.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Administrative reason <span className="font-normal text-gray-500">(optional)</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label>{error && <p className="mt-3 text-sm font-semibold text-rose-600" role="alert">{error}</p>}</DialogShell>;
}

export function AddMemberDialog({ busy, onClose, onLookup, onSubmit }: { busy: boolean; onClose: () => void; onLookup: (email: string) => Promise<ExistingOrganizationUser>; onSubmit: (payload: { email: string; role: OrganizationMemberRole; reason?: string }) => void }) {
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<OrganizationMemberRole>('USER');
  const [reason, setReason] = useState('');
  const [account, setAccount] = useState<ExistingOrganizationUser | null>(null);
  const [error, setError] = useState('');
  const [lookupBusy, setLookupBusy] = useState(false);
  const findAccount = async () => { setError(''); setAccount(null); setLookupBusy(true); try { setAccount(await onLookup(email.trim())); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to find this BSM account.'); } finally { setLookupBusy(false); } };
  return <DialogShell title="Add Member" busy={busy} busyLabel="Adding…" onClose={onClose} onSubmit={() => account ? onSubmit({ email: account.email, role, reason: reason.trim() || undefined }) : setError('Find an existing BSM account before adding a member.')} submitLabel="Add Member"><p className="mt-1 text-sm text-gray-500">Only existing BSM users can be added. This does not create or modify a Firebase Authentication account.</p><label className="mt-5 block text-sm font-bold">Email<input required type="email" value={email} onChange={(event) => { setEmail(event.target.value); setAccount(null); }} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><button type="button" onClick={() => void findAccount()} disabled={busy || lookupBusy || !email.trim()} className="mt-3 rounded-lg border border-blue-200 px-3 py-2 text-xs font-bold text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50">{lookupBusy ? 'Finding…' : 'Find existing account'}</button>{account && <div className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><p className="font-bold">{account.name || 'Existing BSM user'}</p><p>{account.email}</p></div>}<label className="mt-4 block text-sm font-bold">Tenant role<select value={role} onChange={(event) => setRole(event.target.value as OrganizationMemberRole)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"><option value="ADMIN">ADMIN</option><option value="MANAGER">MANAGER</option><option value="USER">USER</option></select></label><label className="mt-4 block text-sm font-bold">Reason <span className="font-normal text-gray-500">(optional)</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label>{error && <p className="mt-3 text-sm font-semibold text-rose-600" role="alert">{error}</p>}</DialogShell>;
}

export function MemberAccessDialog({ member, activeMembers, maxUsers, busy, onClose, onSubmit, onArchive }: { member: OrganizationMember; activeMembers: number; maxUsers: number | null; busy: boolean; onClose: () => void; onSubmit: (payload: { role?: OrganizationMemberRole; status?: typeof memberStatuses[number]; reason?: string }) => void; onArchive?: () => void }) {
  const [role, setRole] = useState<OrganizationMemberRole>(member.role);
  const [status, setStatus] = useState<typeof memberStatuses[number]>(member.status.toLowerCase() as typeof memberStatuses[number]);
  const [reason, setReason] = useState('');
  const [archiveConfirm, setArchiveConfirm] = useState(false);
  return <DialogShell title={`Manage ${member.name || member.email || 'member'}`} busy={busy} onClose={onClose} onSubmit={() => onSubmit({ role, status, reason: reason.trim() || undefined })} submitLabel="Save member access"><p className="mt-1 text-sm text-gray-500">Changes affect workspace membership only, not Firebase Authentication.</p><div className="mt-4 rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900"><div>Active users: <strong>{activeMembers}</strong></div><div>License limit: <strong>{maxUsers ?? '—'}</strong></div><div>Available seats: <strong>{maxUsers === null ? '—' : Math.max(0, maxUsers - activeMembers)}</strong></div></div><label className="mt-5 block text-sm font-bold">Tenant role<select value={role} onChange={(event) => setRole(event.target.value as OrganizationMemberRole)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"><option value="ADMIN">ADMIN</option><option value="MANAGER">MANAGER</option><option value="USER">USER</option></select></label><label className="mt-4 block text-sm font-bold">Membership status<select value={status} onChange={(event) => setStatus(event.target.value as typeof memberStatuses[number])} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100">{memberStatuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Administrative reason <span className="font-normal text-gray-500">(optional)</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label>{onArchive && member.status.toLowerCase() !== 'archived' && <div className="mt-5 border-t border-gray-200 pt-4"><button type="button" onClick={() => setArchiveConfirm(true)} disabled={busy} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700 focus:outline-none focus:ring-2 focus:ring-rose-500">Archive Member</button>{archiveConfirm && <div className="mt-3 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900"><p className="font-bold">Archive member?</p><p className="mt-1">Access will be removed while historical records are preserved.</p><button type="button" onClick={onArchive} disabled={busy} className="mt-3 rounded-lg bg-rose-700 px-3 py-2 text-xs font-bold text-white focus:outline-none focus:ring-2 focus:ring-rose-500">Confirm Archive Member</button></div>}</div>}</DialogShell>;
}

export function MemberActionConfirmDialog({ action, member, busy, onClose, onConfirm }: { action: 'SUSPEND_MEMBER' | 'REACTIVATE_MEMBER' | 'ARCHIVE_MEMBER' | 'RESTORE_MEMBER'; member: OrganizationMember; busy: boolean; onClose: () => void; onConfirm: () => void | Promise<void> }) {
  const labels = { SUSPEND_MEMBER: ['Suspend member access?', 'Suspend Access', 'Access will be suspended and the active seat will be released.'], REACTIVATE_MEMBER: ['Reactivate member access?', 'Reactivate Access', 'This will consume an available active seat.'], ARCHIVE_MEMBER: ['Archive member?', 'Confirm Archive Member', 'Access will be removed while historical records are preserved.'], RESTORE_MEMBER: ['Restore member?', 'Restore Member', 'This will restore active organization access and consume a seat.'] } as const;
  const [title, submitLabel, description] = labels[action];
  return <DialogShell title={title} busy={busy} onClose={onClose} onSubmit={onConfirm} submitLabel={submitLabel} busyLabel={`${submitLabel}…`}><p className="mt-3 text-sm text-gray-600">{member.name || member.email || 'This member'} · {member.email || 'No email available'}</p><p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{description}</p></DialogShell>;
}
