'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Search } from 'lucide-react';
import { getOrganizations } from '@/lib/console-api';
import { evaluateOrganizationLicense } from '@/lib/license';
import { Organization, OrganizationLicenseStatus, OrganizationPlan } from '@/lib/types';
import { EmptyState, ErrorState, formatDate, LoadingState, StatusBadge } from './ConsolePrimitives';

const statuses: Array<'ALL' | OrganizationLicenseStatus> = ['ALL', 'TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED'];
export function OrganizationsModule() {
  const router = useRouter(); const [items, setItems] = useState<Organization[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'ALL' | OrganizationLicenseStatus>('ALL'); const [plan, setPlan] = useState<'ALL' | OrganizationPlan>('ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { getOrganizations().then(setItems).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load organizations.')).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => items.filter((org) => { const evaluation = evaluateOrganizationLicense(org); const q = query.toLowerCase(); return (!q || [org.name, org.slug, org.ownerEmail].some((field) => field?.toLowerCase().includes(q))) && (status === 'ALL' || evaluation.status === status) && (plan === 'ALL' || org.license?.plan === plan); }), [items, plan, query, status]);
  if (loading) return <LoadingState />; if (error) return <ErrorState message={error} />;
  return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-xl border border-gray-200 bg-white p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, slug, or owner email" className="w-full rounded-lg border border-gray-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500" /></div><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="rounded-lg border border-gray-200 px-3 py-2 text-sm">{statuses.map((item) => <option key={item} value={item}>{item === 'ALL' ? 'All license statuses' : item.replace('_', ' ')}</option>)}</select><select value={plan} onChange={(e) => setPlan(e.target.value as typeof plan)} className="rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="ALL">All plans</option><option value="TRIAL">TRIAL</option><option value="STARTER">STARTER</option><option value="TEAM">TEAM</option><option value="LEGACY">LEGACY</option></select></div>{filtered.length === 0 ? <EmptyState title="No organizations found" message="Organizations created by the Client App will appear here." /> : <div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-gray-200 bg-gray-50 text-[10px] uppercase tracking-wider text-gray-500"><tr>{['Business Name', 'Type', 'Owner', 'Plan', 'License', 'Seats', 'Created', 'Expiration', ''].map((h) => <th key={h} className="px-5 py-3 font-black">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{filtered.map((org) => { const evaluation = evaluateOrganizationLicense(org); return <tr key={org.id} className="hover:bg-gray-50"><td className="px-5 py-4"><button onClick={() => router.push(`/organizations/${org.id}`)} className="font-bold text-gray-900 hover:text-blue-600">{org.name}</button><p className="text-xs text-gray-400">{org.slug || 'No slug'}</p></td><td className="px-5 py-4 text-gray-600">{org.businessType || '—'}</td><td className="px-5 py-4 text-gray-600">{org.ownerEmail || '—'}</td><td className="px-5 py-4 font-semibold">{org.license?.plan || '—'}</td><td className="px-5 py-4"><StatusBadge status={evaluation.status} /></td><td className="px-5 py-4">{org.license?.maxUsers ?? '—'}</td><td className="px-5 py-4 text-gray-600">{formatDate(org.createdAt)}</td><td className="px-5 py-4 text-gray-600">{formatDate(org.license?.subscriptionEndsAt || org.license?.trialEndsAt)}</td><td className="px-5 py-4"><button onClick={() => router.push(`/organizations/${org.id}`)} className="text-xs font-bold text-blue-600">View</button></td></tr>; })}</tbody></table></div></div>}</div>;
}
