'use client';

import React, { useEffect, useState } from 'react';
import { fetchMembers, fetchOrganizations } from '@/lib/organization-data';
import { evaluateOrganizationLicense } from '@/lib/license';
import { OrganizationMember, Organization } from '@/lib/types';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from './ConsolePrimitives';

type Row = OrganizationMember & { organization: string; license: ReturnType<typeof evaluateOrganizationLicense>['status'] };
export function UsersModule() { const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { fetchOrganizations().then(async (organizations) => { const grouped = await Promise.all(organizations.map(async (org) => ({ org, members: await fetchMembers(org.id) }))); setRows(grouped.flatMap(({ org, members }) => members.map((member) => ({ ...member, organization: org.name, license: evaluateOrganizationLicense(org).status })))); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load memberships.')).finally(() => setLoading(false)); }, []); const filtered = rows.filter((row) => [row.name, row.email, row.organization].some((value) => value?.toLowerCase().includes(query.toLowerCase()))); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} />; return <div className="space-y-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, email, or organization" className="w-full rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500" />{!filtered.length ? <EmptyState title="No memberships found" message="Memberships remain authoritative under each organization." /> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-gray-200 bg-gray-50 text-[10px] uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3">Name</th><th>Email</th><th>Organization</th><th>Role</th><th>Membership</th><th>License</th></tr></thead><tbody className="divide-y divide-gray-100">{filtered.map((row) => <tr key={`${row.organization}-${row.id}`}><td className="px-5 py-4 font-bold">{row.name || '—'}</td><td>{row.email || '—'}</td><td>{row.organization}</td><td>{row.role}</td><td>{row.status}</td><td><StatusBadge status={row.license} /></td></tr>)}</tbody></table></div>}</div>; }
