import { Customer, Installation, License, InfrastructureMetrics, DeploymentRecord, ActivityRecord, DeveloperUser, Release } from './types';

export const INITIAL_DEVELOPERS: DeveloperUser[] = [
  {
    id: 'dev-1',
    name: 'Alex Vance',
    email: 'alex.vance@bsm-cloud.internal',
    role: 'OWNER',
    avatar: 'https://picsum.photos/seed/alex/120/120',
    lastLogin: '2026-08-18 09:14 UTC',
  },
  {
    id: 'dev-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@bsm-cloud.internal',
    role: 'DEVELOPER',
    avatar: 'https://picsum.photos/seed/sarah/120/120',
    lastLogin: '2026-08-18 08:32 UTC',
  },
  {
    id: 'dev-3',
    name: 'Marcus Brody',
    email: 'marcus.brody@bsm-cloud.internal',
    role: 'SUPPORT',
    avatar: 'https://picsum.photos/seed/marcus/120/120',
    lastLogin: '2026-08-17 18:45 UTC',
  },
];

export const INITIAL_RELEASES: Release[] = [
  { id: 'REL-1', version: 'v1.3.0', releaseDate: '2026-08-01', releaseStatus: 'STABLE', notes: 'Major features and performance improvements.' },
  { id: 'REL-2', version: 'v1.2.0', releaseDate: '2026-06-01', releaseStatus: 'DEPRECATED', notes: 'Legacy version.' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-101',
    name: 'Apex Logistics Corp',
    company: 'Apex Logistics Global',
    orgCode: 'APEX-LOG',
    type: 'Corporate',
    status: 'ACTIVE',
    plan: 'Enterprise',
    primaryContactEmail: 'admin@apexlogistics.io',
    phone: '+1 (555) 123-4567',
    website: 'https://apexlogistics.io',
    address: '123 Supply Chain Way, Chicago, IL',
    country: 'USA',
    internalNotes: 'VIP Customer. High volume.',
    createdAt: '2025-02-15',
    installationsCount: 2,
    totalUsersCount: 340,
  },
  {
    id: 'cust-102',
    name: 'Meridian Global Trade',
    company: 'Meridian Trading Partners',
    orgCode: 'MERIDIAN',
    type: 'Enterprise',
    status: 'ACTIVE',
    plan: 'Enterprise',
    primaryContactEmail: 'tech@meridianglobal.com',
    phone: '+44 20 7123 4567',
    website: 'https://meridianglobal.com',
    address: '45 Trade Plaza, London, UK',
    country: 'UK',
    internalNotes: 'Regular deployments.',
    createdAt: '2025-04-10',
    installationsCount: 1,
    totalUsersCount: 180,
  },
  {
    id: 'cust-103',
    name: 'Vanguard Retail Group',
    company: 'Vanguard Retail Systems',
    orgCode: 'VANGUARD',
    type: 'SMB',
    status: 'ACTIVE',
    plan: 'Business',
    primaryContactEmail: 'it-support@vanguardretail.net',
    phone: '+1 (555) 987-6543',
    website: 'https://vanguardretail.net',
    address: '78 Retail Ave, New York, NY',
    country: 'USA',
    internalNotes: 'Stable.',
    createdAt: '2025-06-20',
    installationsCount: 1,
    totalUsersCount: 95,
  },
  {
    id: 'cust-104',
    name: 'Horizon Health Systems',
    company: 'Horizon Medical Tech',
    orgCode: 'HORIZON-MED',
    type: 'Enterprise',
    status: 'SUSPENDED',
    plan: 'Enterprise',
    primaryContactEmail: 'cloud-ops@horizonhealth.org',
    phone: '+1 (555) 555-0101',
    website: 'https://horizonhealth.org',
    address: '99 Medical Dr, Boston, MA',
    country: 'USA',
    internalNotes: 'Under review.',
    createdAt: '2025-09-01',
    installationsCount: 2,
    totalUsersCount: 220,
  },
  {
    id: 'cust-105',
    name: 'Zenith Capital Partners',
    company: 'Zenith Wealth Management',
    orgCode: 'ZENITH-CAP',
    type: 'Corporate',
    status: 'ACTIVE',
    plan: 'Business',
    primaryContactEmail: 'sysadmin@zenithcap.com',
    phone: '+1 (555) 321-7890',
    website: 'https://zenithcap.com',
    address: '500 Finance Tower, Charlotte, NC',
    country: 'USA',
    internalNotes: 'Financial services.',
    createdAt: '2025-11-12',
    installationsCount: 1,
    totalUsersCount: 60,
  },
  {
    id: 'cust-106',
    name: 'Pinnacle Dynamics',
    company: 'Pinnacle Engineering & Mfg',
    orgCode: 'PINNACLE',
    type: 'SMB',
    status: 'ACTIVE',
    plan: 'Growth',
    primaryContactEmail: 'devops@pinnacledynamics.co',
    phone: '+49 30 123456',
    website: 'https://pinnacledynamics.co',
    address: '10 Industrial Park, Berlin, DE',
    country: 'Germany',
    internalNotes: 'Growing fast.',
    createdAt: '2026-01-05',
    installationsCount: 1,
    totalUsersCount: 45,
  },
  {
    id: 'cust-107',
    name: 'Quantum Freight Solutions',
    company: 'Quantum Transport',
    orgCode: 'QUANTUM-FRT',
    type: 'SMB',
    status: 'TRIAL',
    plan: 'Trial',
    primaryContactEmail: 'it@quantumfreight.io',
    phone: '+65 6789 0123',
    website: 'https://quantumfreight.io',
    address: '1 Port Link, Singapore',
    country: 'Singapore',
    internalNotes: 'Trial period.',
    createdAt: '2026-07-10',
    installationsCount: 1,
    totalUsersCount: 25,
  },
];

export const INITIAL_INSTALLATIONS: Installation[] = [
  {
    id: 'BSM-1001-001',
    name: 'Primary Instance',
    customerId: 'cust-101',
    customerName: 'Apex Logistics Corp',
    domain: 'apex-sales.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-central1',
    cloudProject: 'bsm-prod-apex-01',
    firebaseProject: 'bsm-fb-apex-01',
    cloudRunService: 'bsm-core-apex',
    dbStatus: 'Connected',
    storageUsedMb: 4200,
    storageLimitMb: 25000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'CURRENT',
    health: 'HEALTHY',
    licenseId: 'LIC-8801',
    lastHeartbeat: '12 seconds ago',
    createdAt: '2025-02-18',
    activeUsersNow: 48,
    totalLeadsCount: 14200,
  },
    {
    id: 'BSM-1001-002',
    name: 'Secondary Instance',
    customerId: 'cust-101',
    customerName: 'Apex Logistics Corp',
    domain: 'apex-eu.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'europe-west1',
    cloudProject: 'bsm-prod-apex-eu',
    firebaseProject: 'bsm-fb-apex-eu',
    cloudRunService: 'bsm-core-apex-eu',
    dbStatus: 'Connected',
    storageUsedMb: 2800,
    storageLimitMb: 25000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'CURRENT',
    health: 'HEALTHY',
    licenseId: 'LIC-8802',
    lastHeartbeat: '28 seconds ago',
    createdAt: '2025-05-12',
    activeUsersNow: 22,
    totalLeadsCount: 8900,
  },
  {
    id: 'BSM-1002-001',
    name: 'Meridian Global',
    customerId: 'cust-102',
    customerName: 'Meridian Global Trade',
    domain: 'meridian.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-east1',
    cloudProject: 'bsm-prod-meridian',
    firebaseProject: 'bsm-fb-meridian',
    cloudRunService: 'bsm-core-meridian',
    dbStatus: 'Connected',
    storageUsedMb: 6100,
    storageLimitMb: 50000,
    appVersion: 'v2.8.3',
    deploymentStatus: 'UPDATE_AVAILABLE',
    health: 'ATTENTION',
    licenseId: 'LIC-8803',
    lastHeartbeat: '3 minutes ago',
    createdAt: '2025-04-12',
    activeUsersNow: 31,
    totalLeadsCount: 24500,
  },
  {
    id: 'BSM-1003-001',
    name: 'Vanguard Primary',
    customerId: 'cust-103',
    customerName: 'Vanguard Retail Group',
    domain: 'vanguard.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-west1',
    cloudProject: 'bsm-prod-vanguard',
    firebaseProject: 'bsm-fb-vanguard',
    cloudRunService: 'bsm-core-vanguard',
    dbStatus: 'Connected',
    storageUsedMb: 1950,
    storageLimitMb: 10000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'CURRENT',
    health: 'HEALTHY',
    licenseId: 'LIC-8804',
    lastHeartbeat: '8 seconds ago',
    createdAt: '2025-06-22',
    activeUsersNow: 14,
    totalLeadsCount: 5200,
  },
  {
    id: 'BSM-1004-001',
    name: 'Horizon East',
    customerId: 'cust-104',
    customerName: 'Horizon Health Systems',
    domain: 'horizon-east.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-east4',
    cloudProject: 'bsm-prod-horizon-e',
    firebaseProject: 'bsm-fb-horizon-e',
    cloudRunService: 'bsm-core-horizon-e',
    dbStatus: 'Degraded',
    storageUsedMb: 12400,
    storageLimitMb: 50000,
    appVersion: 'v2.8.2',
    deploymentStatus: 'UPDATE_AVAILABLE',
    health: 'ATTENTION',
    licenseId: 'LIC-8805',
    lastHeartbeat: '45 seconds ago',
    createdAt: '2025-09-05',
    activeUsersNow: 42,
    totalLeadsCount: 31000,
  },
  {
    id: 'BSM-1004-002',
    name: 'Horizon West',
    customerId: 'cust-104',
    customerName: 'Horizon Health Systems',
    domain: 'horizon-west.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-west2',
    cloudProject: 'bsm-prod-horizon-w',
    firebaseProject: 'bsm-fb-horizon-w',
    cloudRunService: 'bsm-core-horizon-w',
    dbStatus: 'Disconnected',
    storageUsedMb: 9100,
    storageLimitMb: 50000,
    appVersion: 'v2.7.9',
    deploymentStatus: 'FAILED',
    health: 'CRITICAL',
    licenseId: 'LIC-8806',
    lastHeartbeat: '18 minutes ago',
    createdAt: '2025-10-15',
    activeUsersNow: 0,
    totalLeadsCount: 19400,
  },
  {
    id: 'BSM-1005-001',
    name: 'Zenith Primary',
    customerId: 'cust-105',
    customerName: 'Zenith Capital Partners',
    domain: 'zenith.bsm-app.net',
    environment: 'PRODUCTION',
    region: 'us-central1',
    cloudProject: 'bsm-prod-zenith',
    firebaseProject: 'bsm-fb-zenith',
    cloudRunService: 'bsm-core-zenith',
    dbStatus: 'Connected',
    storageUsedMb: 1450,
    storageLimitMb: 10000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'CURRENT',
    health: 'HEALTHY',
    licenseId: 'LIC-8807',
    lastHeartbeat: '15 seconds ago',
    createdAt: '2025-11-14',
    activeUsersNow: 9,
    totalLeadsCount: 3400,
  },
  {
    id: 'BSM-1006-001',
    name: 'Pinnacle Core',
    customerId: 'cust-106',
    customerName: 'Pinnacle Dynamics',
    domain: 'pinnacle.bsm-app.net',
    environment: 'STAGING',
    region: 'europe-west3',
    cloudProject: 'bsm-prod-pinnacle',
    firebaseProject: 'bsm-fb-pinnacle',
    cloudRunService: 'bsm-core-pinnacle',
    dbStatus: 'Connected',
    storageUsedMb: 890,
    storageLimitMb: 5000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'DEPLOYING',
    health: 'HEALTHY',
    licenseId: 'LIC-8808',
    lastHeartbeat: 'Just now',
    createdAt: '2026-01-08',
    activeUsersNow: 6,
    totalLeadsCount: 1850,
  },
  {
    id: 'BSM-1007-001',
    name: 'Quantum Trial',
    customerId: 'cust-107',
    customerName: 'Quantum Freight Solutions',
    domain: 'quantum.bsm-app.net',
    environment: 'DEVELOPMENT',
    region: 'us-central1',
    cloudProject: 'bsm-prod-quantum',
    firebaseProject: 'bsm-fb-quantum',
    cloudRunService: 'bsm-core-quantum',
    dbStatus: 'Connected',
    storageUsedMb: 340,
    storageLimitMb: 2000,
    appVersion: 'v2.8.4',
    deploymentStatus: 'CURRENT',
    health: 'UNKNOWN',
    licenseId: 'LIC-8809',
    lastHeartbeat: '2 hours ago',
    createdAt: '2026-07-12',
    activeUsersNow: 0,
    totalLeadsCount: 410,
  },
];

export const INITIAL_LICENSES: License[] = [
  {
    id: 'LIC-8801',
    installationId: 'BSM-1001-001',
    customerId: 'cust-101',
    status: 'ACTIVE',
    planName: 'Enterprise Unlimited',
    seatsLimit: 250,
    seatsUsed: 198,
    expiresAt: '2027-02-15',
    licenseKeyMasked: 'BSM-ENT-9941-XXXX-8801',
    issuedAt: '2025-02-15T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-02-15T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8802',
    installationId: 'BSM-1001-002',
    customerId: 'cust-101',
    status: 'ACTIVE',
    planName: 'Enterprise Regional EU',
    seatsLimit: 100,
    seatsUsed: 74,
    expiresAt: '2027-02-15',
    licenseKeyMasked: 'BSM-ENT-EU88-XXXX-8802',
    issuedAt: '2025-05-12T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-05-12T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8803',
    installationId: 'BSM-1002-001',
    customerId: 'cust-102',
    status: 'EXPIRING',
    planName: 'Enterprise Standard',
    seatsLimit: 200,
    seatsUsed: 165,
    expiresAt: '2026-09-01',
    licenseKeyMasked: 'BSM-ENT-4421-XXXX-8803',
    issuedAt: '2025-04-12T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-04-12T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8804',
    installationId: 'BSM-1003-001',
    customerId: 'cust-103',
    status: 'ACTIVE',
    planName: 'Business Pro',
    seatsLimit: 100,
    seatsUsed: 88,
    expiresAt: '2027-06-20',
    licenseKeyMasked: 'BSM-BUS-3319-XXXX-8804',
    issuedAt: '2025-06-20T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-06-20T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8805',
    installationId: 'BSM-1004-001',
    customerId: 'cust-104',
    status: 'ACTIVE',
    planName: 'Enterprise Health Cluster',
    seatsLimit: 150,
    seatsUsed: 132,
    expiresAt: '2027-09-01',
    licenseKeyMasked: 'BSM-MED-7712-XXXX-8805',
    issuedAt: '2025-09-01T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8806',
    installationId: 'BSM-1004-002',
    customerId: 'cust-104',
    status: 'SUSPENDED',
    planName: 'Enterprise Health West',
    seatsLimit: 100,
    seatsUsed: 0,
    expiresAt: '2027-09-01',
    licenseKeyMasked: 'BSM-MED-7713-XXXX-8806',
    issuedAt: '2025-10-15T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-10-15T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8807',
    installationId: 'BSM-1005-001',
    customerId: 'cust-105',
    status: 'ACTIVE',
    planName: 'Business Finance',
    seatsLimit: 75,
    seatsUsed: 54,
    expiresAt: '2026-11-14',
    licenseKeyMasked: 'BSM-FIN-5510-XXXX-8807',
    issuedAt: '2025-11-14T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2025-11-14T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8808',
    installationId: 'BSM-1006-001',
    customerId: 'cust-106',
    status: 'ACTIVE',
    planName: 'Growth Manufacturing',
    seatsLimit: 50,
    seatsUsed: 42,
    expiresAt: '2027-01-08',
    licenseKeyMasked: 'BSM-GRW-1120-XXXX-8808',
    issuedAt: '2026-01-08T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2026-01-08T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
  {
    id: 'LIC-8809',
    installationId: 'BSM-1007-001',
    customerId: 'cust-107',
    status: 'EXPIRED',
    planName: 'Trial Evaluation',
    seatsLimit: 30,
    seatsUsed: 25,
    expiresAt: '2026-08-10',
    licenseKeyMasked: 'BSM-TRL-9900-XXXX-8809',
    issuedAt: '2026-07-10T00:00:00Z',
    lastChecked: '2026-08-18T06:00:00Z',
    createdAt: '2026-07-10T00:00:00Z',
    updatedAt: '2026-08-18T06:00:00Z',
  },
];

export const INITIAL_INFRASTRUCTURE: InfrastructureMetrics[] = [
  {
    installationId: 'BSM-1001-001',
    cloudRunStatus: 'Ready',
    cpuAllocation: '2 vCPU',
    memoryMb: 4096,
    minInstances: 2,
    maxInstances: 10,
    firestoreRegion: 'us-central1',
    storageUsedGb: 4.2,
    activeConnections: 48,
    errorRate5xx: 0.01,
    averageLatencyMs: 44,
    lastChecked: 'Just now',
  },
  {
    installationId: 'BSM-1001-002',
    cloudRunStatus: 'Ready',
    cpuAllocation: '2 vCPU',
    memoryMb: 4096,
    minInstances: 1,
    maxInstances: 8,
    firestoreRegion: 'europe-west1',
    storageUsedGb: 2.8,
    activeConnections: 22,
    errorRate5xx: 0.0,
    averageLatencyMs: 58,
    lastChecked: 'Just now',
  },
  {
    installationId: 'BSM-1002-001',
    cloudRunStatus: 'Ready',
    cpuAllocation: '4 vCPU',
    memoryMb: 8192,
    minInstances: 2,
    maxInstances: 15,
    firestoreRegion: 'us-east1',
    storageUsedGb: 6.1,
    activeConnections: 31,
    errorRate5xx: 0.25,
    averageLatencyMs: 112,
    lastChecked: '1 min ago',
  },
  {
    installationId: 'BSM-1003-001',
    cloudRunStatus: 'Ready',
    cpuAllocation: '1 vCPU',
    memoryMb: 2048,
    minInstances: 1,
    maxInstances: 5,
    firestoreRegion: 'us-west1',
    storageUsedGb: 1.9,
    activeConnections: 14,
    errorRate5xx: 0.0,
    averageLatencyMs: 38,
    lastChecked: 'Just now',
  },
  {
    installationId: 'BSM-1004-001',
    cloudRunStatus: 'Scaling',
    cpuAllocation: '2 vCPU',
    memoryMb: 4096,
    minInstances: 2,
    maxInstances: 12,
    firestoreRegion: 'us-east4',
    storageUsedGb: 12.4,
    activeConnections: 42,
    errorRate5xx: 1.85,
    averageLatencyMs: 240,
    lastChecked: '2 mins ago',
  },
  {
    installationId: 'BSM-1004-002',
    cloudRunStatus: 'Error',
    cpuAllocation: '2 vCPU',
    memoryMb: 4096,
    minInstances: 1,
    maxInstances: 8,
    firestoreRegion: 'us-west2',
    storageUsedGb: 9.1,
    activeConnections: 0,
    errorRate5xx: 100.0,
    averageLatencyMs: 0,
    lastChecked: '18 mins ago',
  },
  {
    installationId: 'BSM-1005-001',
    cloudRunStatus: 'Ready',
    cpuAllocation: '1 vCPU',
    memoryMb: 2048,
    minInstances: 1,
    maxInstances: 6,
    firestoreRegion: 'us-central1',
    storageUsedGb: 1.4,
    activeConnections: 9,
    errorRate5xx: 0.0,
    averageLatencyMs: 35,
    lastChecked: 'Just now',
  },
  {
    installationId: 'BSM-1006-001',
    cloudRunStatus: 'Updating',
    cpuAllocation: '2 vCPU',
    memoryMb: 4096,
    minInstances: 1,
    maxInstances: 6,
    firestoreRegion: 'europe-west3',
    storageUsedGb: 0.8,
    activeConnections: 6,
    errorRate5xx: 0.04,
    averageLatencyMs: 51,
    lastChecked: 'Just now',
  },
  {
    installationId: 'BSM-1007-001',
    cloudRunStatus: 'Ready',
    cpuAllocation: '1 vCPU',
    memoryMb: 2048,
    minInstances: 0,
    maxInstances: 3,
    firestoreRegion: 'us-central1',
    storageUsedGb: 0.3,
    activeConnections: 0,
    errorRate5xx: 0.0,
    averageLatencyMs: 0,
    lastChecked: '2 hours ago',
  },
];

export const INITIAL_DEPLOYMENTS: DeploymentRecord[] = [
  {
    id: 'DEP-901',
    installationId: 'BSM-1001-001',
    version: 'v2.8.4',
    targetVersion: 'v2.8.4',
    status: 'CURRENT',
    initiatedBy: 'Alex Vance',
    deployedAt: '2026-08-10 14:22 UTC',
    releaseNotes: 'Performance patch for lead scoring pipeline & security hardening.',
  },
  {
    id: 'DEP-902',
    installationId: 'BSM-1002-001',
    version: 'v2.8.3',
    targetVersion: 'v2.8.4',
    status: 'UPDATE_AVAILABLE',
    initiatedBy: 'System Registry',
    deployedAt: '2026-07-15 09:10 UTC',
    releaseNotes: 'Upgrade available for enhanced CRM sync connectors.',
  },
  {
    id: 'DEP-903',
    installationId: 'BSM-1004-002',
    version: 'v2.7.9',
    targetVersion: 'v2.8.4',
    status: 'FAILED',
    initiatedBy: 'Sarah Chen',
    deployedAt: '2026-08-18 05:12 UTC',
    releaseNotes: 'Migration timeout on Cloud SQL / Firestore schema lock. Rollback recommended.',
  },
  {
    id: 'DEP-904',
    installationId: 'BSM-1006-001',
    version: 'v2.8.3',
    targetVersion: 'v2.8.4',
    status: 'DEPLOYING',
    initiatedBy: 'Alex Vance',
    deployedAt: '2026-08-18 05:48 UTC',
    releaseNotes: 'Rolling deployment of BSM core container v2.8.4.',
  },
];

export const INITIAL_ACTIVITIES: ActivityRecord[] = [
  {
    id: 'ACT-501',
    timestamp: '2026-08-18 05:48 UTC',
    action: 'DEPLOYMENT_STARTED',
    type: 'DEPLOYMENT',
    severity: 'INFO',
    installationId: 'BSM-1006-001',
    customerName: 'Pinnacle Dynamics',
    description: 'Triggered rolling update to version v2.8.4 on cloud run service bsm-core-pinnacle.',
    actor: 'Alex Vance',
  },
  {
    id: 'ACT-502',
    timestamp: '2026-08-18 05:12 UTC',
    action: 'INFRASTRUCTURE_WARNING',
    type: 'HEALTH',
    severity: 'ERROR',
    installationId: 'BSM-1004-002',
    customerName: 'Horizon Health Systems',
    description: 'Installation health degraded to CRITICAL. Cloud Run container unresponsive in us-west2.',
    actor: 'Cloud Monitor Sentinel',
  },
  {
    id: 'ACT-503',
    timestamp: '2026-08-18 04:30 UTC',
    action: 'LICENSE_RENEWED',
    type: 'LICENSE',
    severity: 'SUCCESS',
    installationId: 'BSM-1003-001',
    customerName: 'Vanguard Retail Group',
    description: 'License renewal verified. Expiry extended to June 20, 2027.',
    actor: 'Marcus Brody',
  },
  {
    id: 'ACT-504',
    timestamp: '2026-08-18 02:15 UTC',
    action: 'INFRASTRUCTURE_WARNING',
    type: 'SECURITY',
    severity: 'WARN',
    installationId: 'BSM-1002-001',
    customerName: 'Meridian Global Trade',
    description: 'Elevated 5xx error rate detected (0.25%). Investigating API gateway routing.',
    actor: 'Sarah Chen',
  },
  {
    id: 'ACT-505',
    timestamp: '2026-08-17 21:05 UTC',
    action: 'CONFIGURATION_CHANGED',
    type: 'CONFIG',
    severity: 'INFO',
    installationId: 'BSM-1001-001',
    customerName: 'Apex Logistics Corp',
    description: 'Updated Firestore region backup policy and TTL retention rules.',
    actor: 'Alex Vance',
  },
];
